## This runs testme test script inst/testme/test-foreach_dofuture,cluster-missing-doFuture-pkg.R
## Don't edit - it was autogenerated by inst/testme/deploy.R
doFuture:::testme("foreach_dofuture,cluster-missing-doFuture-pkg")
